orchestrator:
  connector:
    database:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/com.globallogic.orchestrator.config
      login: root
      password: yroot
      enabled: true

    filesystem:
      enabled: true

    mongodb:
      host: 127.0.0.1
      port: 27017
      databaseName: com.globallogic.orchestrator.config
      enabled: true

  controller:
    enabled: true

  dao:
    database:
      enabled: true
    filesystem:
      enabled: true
    mongodb:
      enabled: true

  service:
    enabled: true